name: Update Prod Dependencies

on:
  workflow_dispatch:
  repository_dispatch:
    types: [stage_updates_merged]

permissions:
  id-token: write
  contents: read

jobs:
  patcher:
    if: github.event_name == 'repository_dispatch' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: gruntwork-io/patcher-action/.github/workflows/patcher.yml@v4
    with:
      working_dir: ./
      include_dirs: "{*prod*}/**"
    secrets:
      PIPELINES_READ_TOKEN: ${{ secrets.PIPELINES_READ_TOKEN }}
      PR_CREATE_TOKEN: ${{ secrets.PR_CREATE_TOKEN }}
