name: "Gruntwork Patcher"
description: "Setup and run Patcher to update Terraform and Terragrunt dependencies."
author: "Gruntwork"

branding:
  icon: chevron-right
  color: purple

inputs:
  github_token:
    description: "GitHub's Personal Access Token (PAT). Defaults to GITHUB_TOKEN."
    default: ${{ github.token }}
  patcher_command:
    description: "Patcher command to run. Valid options: 'update' or 'report'."
    default: "update"
  update_strategy:
    description: "Update strategy. Only used when running 'update'. Defaults to 'next-breaking'."
    default: "next-breaking"
  dependency:
    description: >
      "Target the update to a single dependency. Format: <org>/<repo>/<name>."
      "Example: gruntwork-io/terraform-aws-service-catalog/services/ecs-module."
  working_dir:
    description: "Directory where Patcher should run. If empty, it will run in the whole repo."
  working_dirs:
    description: "Directories where Patcher should run. If empty, it will default to `working_dir` above."
  commit_author:
    description: >
      "Author of the Pull Request's commits in the format 'Name <name@email.com>'. The permissions to push the changes
      "and to create the Pull Request are from 'github_token'. Defaults to gruntwork-patcher."
    default: "gruntwork-patcher-bot <patcher@gruntwork.io>"

outputs:
  dependencies:
    description: "Terraform and Terragrunt dependencies from the given directory. Only works for 'report'."

runs:
  using: "node20"
  main: "dist/index.js"
