name: "Gruntwork Patcher"
description: "Setup and run Patcher to update Terraform and Terragrunt dependencies."
author: "Gruntwork"

branding:
  icon: chevron-right
  color: purple

inputs:
  github_token:
    description: "Personal Access Token (PAT) used to download binaries and publish pull requests. For GitHub, use a Personal Access Token with appropriate repository permissions."
    required: false
  read_token:
    description: "Personal Access Token (PAT) used for 'report' and 'update' to ingest dependencies and their updated versions. If left unset, github_token will be used."
    required: false
  update_token:
    description: "Personal Access Token (PAT) used for 'update' to publish PRs against the relevant repo. If left unset, github_token will be used."
    required: false
  github_base_url:
    description: "Base URL for GitHub (e.g., 'https://github.company.com' or 'http://github.company.com' for GitHub Enterprise). Defaults to 'https://github.com' for GitHub.com."
    required: false
    default: "https://github.com"
  github_org:
    description: "Organization name in GitHub where resources like the Patcher CLI can be downloaded. Defaults to 'gruntwork-io'."
    required: false
    default: "gruntwork-io"
  patcher_command:
    description: "Patcher command to run. Valid options: 'update' or 'report'."
    default: "update"
  patcher_git_repo:
    description: "Repository name for downloading patcher cli. Defaults to 'patcher-cli'."
    required: false
    default: "patcher-cli"
  patcher_version:
    description: "Version of Patcher to use. Defaults to the v0.16.0 version."
    required: false
    default: "v0.16.0"
  terrapatch_git_repo:
    description: "Repository name for downloading terrapatch cli. Defaults to 'terrapatch-cli'."
    required: false
    default: "terrapatch-cli"
  terrapatch_version:
    description: "Version of terrapatch to use. Defaults to the v0.1.6 version."
    required: false
    default: "v0.1.6"
  terrapatch_github_org:
    description: "Organization name for terrapatch repository in GitHub. Defaults to same as github_org."
    required: false
    default: ""
  include_dirs:
    description: >
      "Include only directories matching the given double-star glob pattern. Only works for `report`."
      "Example: `{*dev*}/**`"
    default: ""
  exclude_dirs:
    description: >
      "Exclude any directories matching the given double-star glob pattern. Only works for `report`."
      "Example: `"{*alb*}/**"`"
    default: ""
  update_strategy:
    description: "Update strategy. Only used when running 'update'. Defaults to 'next-breaking'."
    default: "next-breaking"
  spec_file:
    description: "Default name of the upgrade specification."
    default: "spec.json"
  dependency:
    description: >
      "Limit the update to a single dependency. Format: <org>/<repo>/<name>."
      "Example: gruntwork-io/terraform-aws-service-catalog/services/ecs-module."
  working_dir:
    description: "Directory where Patcher should run. If empty, it will run in the whole repo."
  commit_author:
    description: >
      "Author of the Pull Request's commits in the format 'Name <name@email.com>'. The permissions to push the changes
      "and to create the Pull Request are from 'github_token'. Defaults to gruntwork-patcher-bot."
    default: "gruntwork-patcher-bot <patcher@gruntwork.io>"
  pull_request_branch:
    description: "Branch where the Pull Request should be created. Required when 'update' is used."
    default: ""
  pull_request_title:
    description: "Title of the Pull Request. Defaults to '[Patcher] Update dependencies'."
    default: "[Patcher] Update dependencies"
  dry_run:
    description: "Simulate all operations using dry-run mode. Useful for test workflows. Defaults to false."
    default: "false"
  no_color:
    description: "Disable color output. Defaults to false."
    default: "false"

outputs:
  dependencies:
    description: "Terraform and Terragrunt dependencies from the given directory. Only works for 'report'."

runs:
  using: "node20"
  main: "dist/index.js"
