name: "Patcher Action"
description: "Run Patcher commands"
author: "Gruntwork.io <grunty@gruntwork.io>"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  patcher_command:
    description: "Patcher command to run. Valid options: 'update' or 'report'. Defaults to 'update'."
  update_strategy:
    description: "Update strategy. Only used when running 'update'. Defaults to 'next-safe'."
  dependency:
    description: "Target the update to a single dependency. Format: <org>/<repo>/<name>. Example: gruntwork-io/terraform-aws-service-catalog/services/ecs-module."
  working_dir:
    description: "Directory where Patcher should run. If empty, it will run in the whole repo."

outputs:
  dependencies:
    description: "Terraform and Terragrunt dependencies from the given directory. Only works for 'report'."

runs:
  using: 'node16'
  main: './dist/index.js'

