name: CI

on:
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  patcher:
    if: github.event_name == 'repository_dispatch' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/patcher.yml
    with:
      include_dirs: "infrastructure-live/**"
      dry_run: true
    secrets:
      PIPELINES_READ_TOKEN: ${{ secrets.PIPELINES_READ_TOKEN }}
      PR_CREATE_TOKEN: ${{ secrets.PR_CREATE_TOKEN }}
